---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md
highlighter: pygments

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

### content configuration ###
title:       "CU CS VM"
keywords:    "Colorado, Virtual Machine, VM, CU CS VM, CU, CU CS"
description: "CU CS Virtual Machine Info"
source_link: "https://github.com/ethanhanner/cu-cs-vm-site"
favicon:     "img/favicon.ico"
touch_icon:  "img/touch.png"
google_analytics_key: "UA-38165152-2"
baseurl: "/vm/"
url: "https://foundation.cs.colorado.edu"

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49b0f0'
  green:     '#309050'
  purple:    '#d070c0'
  orange:    '#f0b030'
  turquoise: '#00C0C0'

kramdown:
  auto_ids:  false
